export type LocaleTitles = {
  [P in LanguageCodes]?: string;
}

/**
 * NOTE:
 * To denote Chapter Translation language,
 * translated fields such as Titles and Descriptions,
 * the API expects a 2-letter language code in accordance with the ISO 639-1 standard.
 *
 * Additionally, some cases require the 5-letter extension if the alpha-2 code is not sufficient
 * to determine the correct sub-type of a language,
 * in the style of `$language-$region`, e.g. zh-hk or pt-br.
 *
 * Because there is no standardized method of denoting romanized translations,
 * we chose to append the `-ro` suffix.
 * For example the romanized version of 五等分の花嫁
 * is 5Toubun no Hanayome or Gotoubun no Hanayome.
 *
 * Both would have the `ja-ro` language code,
 * alternative versions are inserted as alternative titles.
 * This is a clear distinction from
 * the localized en translation The Quintessential Quintuplets.
 */
export type LanguageCodes = ISO6391Codes | MangaDexLanguageCodeVariant;

enum MangaDexLanguageCodeVariant {
  'zh' = 'Simplified Chinese',
  'zh-hk' = 'Traditional Chinese',
  'pt-br' = 'Brazilian Portugese',
  'es' = 'Castilian Spanish',
  'es-la' = 'Latin American Spanish',
  'ja-ro' = 'Romanized Japanese',
  'ko-ro' = 'Romanized Korean',
  'zh-ro' = 'Romanized Chinese'
}

enum ISO6391Codes {
  'aa' = 'Afar',
  'ab' = 'Abkhaz',
  'ae' = 'Avestan',
  'af' = 'Afrikaans',
  'ak' = 'Akan',
  'am' = 'Amharic',
  'an' = 'Aragonese',
  'ar' = 'Arabic',
  'as' = 'Assamese',
  'av' = 'Avaric',
  'ay' = 'Aymara',
  'az' = 'Azerbaijani',
  'ba' = 'Bashkir',
  'be' = 'Belarusian',
  'bg' = 'Bulgarian',
  'bi' = 'Bislama',
  'bm' = 'Bambara',
  'bn' = 'Bengali',
  'bo' = 'Tibetan',
  'br' = 'Breton',
  'bs' = 'Bosnian',
  'ca' = 'Catalan',
  'ce' = 'Chechen',
  'ch' = 'Chamorro',
  'co' = 'Corsican',
  'cr' = 'Cree',
  'cs' = 'Czech',
  'cu' = 'Old_Church_Slavonic',
  'cv' = 'Chuvash',
  'cy' = 'Welsh',
  'da' = 'Danish',
  'de' = 'German',
  'dv' = 'Divehi',
  'dz' = 'Dzongkha',
  'ee' = 'Ewe',
  'el' = 'Greek',
  'en' = 'English',
  'eo' = 'Esperanto',
  'et' = 'Estonian',
  'eu' = 'Basque',
  'fa' = 'Persian',
  'ff' = 'Fula',
  'fi' = 'Finnish',
  'fj' = 'Fijian',
  'fo' = 'Faroese',
  'fr' = 'French',
  'fy' = 'Western_Frisian',
  'ga' = 'Irish',
  'gd' = 'Scottish_Gaelic',
  'gl' = 'Galician',
  'gn' = 'Guaraní',
  'gu' = 'Gujarati',
  'gv' = 'Manx',
  'ha' = 'Hausa',
  'he' = 'Hebrew',
  'hi' = 'Hindi',
  'ho' = 'Hiri_Motu',
  'hr' = 'Croatian',
  'ht' = 'Haitian',
  'hu' = 'Hungarian',
  'hy' = 'Armenian',
  'hz' = 'Herero',
  'ia' = 'Interlingua',
  'id' = 'Indonesian',
  'ie' = 'Interlingue',
  'ig' = 'Igbo',
  'ii' = 'Nuosu',
  'ik' = 'Inupiaq',
  'io' = 'Ido',
  'is' = 'Icelandic',
  'it' = 'Italian',
  'iu' = 'Inuktitut',
  'ja' = 'Japanese',
  'jv' = 'Javanese',
  'ka' = 'Georgian',
  'kg' = 'Kongo',
  'ki' = 'Kikuyu',
  'kj' = 'Kwanyama',
  'kk' = 'Kazakh',
  'kl' = 'Kalaallisut',
  'km' = 'Khmer',
  'kn' = 'Kannada',
  'ko' = 'Korean',
  'kr' = 'Kanuri',
  'ks' = 'Kashmiri',
  'ku' = 'Kurdish',
  'kv' = 'Komi',
  'kw' = 'Cornish',
  'ky' = 'Kyrgyz',
  'la' = 'Latin',
  'lb' = 'Luxembourgish',
  'lg' = 'Ganda',
  'li' = 'Limburgish',
  'ln' = 'Lingala',
  'lo' = 'Lao',
  'lt' = 'Lithuanian',
  'lu' = 'Luba-Katanga',
  'lv' = 'Latvian',
  'mg' = 'Malagasy',
  'mh' = 'Marshallese',
  'mi' = 'Māori',
  'mk' = 'Macedonian',
  'ml' = 'Malayalam',
  'mn' = 'Mongolian',
  'mr' = 'Marathi',
  'ms' = 'Malay',
  'mt' = 'Maltese',
  'my' = 'Burmese',
  'na' = 'Nauru',
  'nb' = 'Norwegian_Bokmål',
  'nd' = 'Northern_Ndebele',
  'ne' = 'Nepali',
  'ng' = 'Ndonga',
  'nl' = 'Dutch',
  'nn' = 'Norwegian_Nynorsk',
  'no' = 'Norwegian',
  'nr' = 'Southern_Ndebele',
  'nv' = 'Navajo',
  'ny' = 'Chichewa',
  'oc' = 'Occitan',
  'oj' = 'Ojibwe',
  'om' = 'Oromo',
  'or' = 'Oriya',
  'os' = 'Ossetian',
  'pa' = 'Panjabi',
  'pi' = 'Pāli',
  'pl' = 'Polish',
  'ps' = 'Pashto',
  'pt' = 'Portuguese',
  'qu' = 'Quechua',
  'rm' = 'Romansh',
  'rn' = 'Kirundi',
  'ro' = 'Romanian',
  'ru' = 'Russian',
  'rw' = 'Kinyarwanda',
  'sa' = 'Sanskrit',
  'sc' = 'Sardinian',
  'sd' = 'Sindhi',
  'se' = 'Northern_Sami',
  'sg' = 'Sango',
  'si' = 'Sinhala',
  'sk' = 'Slovak',
  'sl' = 'Slovenian',
  'sm' = 'Samoan',
  'sn' = 'Shona',
  'so' = 'Somali',
  'sq' = 'Albanian',
  'sr' = 'Serbian',
  'ss' = 'Swati',
  'st' = 'Southern_Sotho',
  'su' = 'Sundanese',
  'sv' = 'Swedish',
  'sw' = 'Swahili',
  'ta' = 'Tamil',
  'te' = 'Telugu',
  'tg' = 'Tajik',
  'th' = 'Thai',
  'ti' = 'Tigrinya',
  'tk' = 'Turkmen',
  'tl' = 'Tagalog',
  'tn' = 'Tswana',
  'to' = 'Tonga',
  'tr' = 'Turkish',
  'ts' = 'Tsonga',
  'tt' = 'Tatar',
  'tw' = 'Twi',
  'ty' = 'Tahitian',
  'ug' = 'Uyghur',
  'uk' = 'Ukrainian',
  'ur' = 'Urdu',
  'uz' = 'Uzbek',
  've' = 'Venda',
  'vi' = 'Vietnamese',
  'vo' = 'Volapük',
  'wa' = 'Walloon',
  'wo' = 'Wolof',
  'xh' = 'Xhosa',
  'yi' = 'Yiddish',
  'yo' = 'Yoruba',
  'za' = 'Zhuang',
  'zu' = 'Zulu',
}


